### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by jkuchar**
- [x] updated readme
- [x] @jakubsarmir add diagrams
- [x] define project goals

### CODE REVIEW

**Comment by jkuchar** [comment]
@charlliz @jakubsarmir @rtrembecky please, all of you read this peace of documentation. By accepting this PR things in documentation will be our rules.

If there will be need to change them, there must be another PR where we will accept new rules.

**Comment by charlliz** [comment]
Ok I read that document, I think it's fine.

**Comment by rtrembecky** [comment]
The document looks ok, but didn't we rework the use case diagram last time in the class? We drew it on paper... I think we got rid of these extends and "manage cars" use case and it made better sense to me.

**Comment by jakubsarmir** [comment]
I'll change it and update

**Pull request merged**
